"""
Application-wide constants and configuration values.
"""

# UI Dimensions
WINDOW_WIDTH = 900
WINDOW_HEIGHT = 700
WINDOW_MIN_WIDTH = 600
WINDOW_MIN_HEIGHT = 500

# Colors
COLOR_PRIMARY = "#1976D2"
COLOR_ERROR = "#D32F2F"
COLOR_SUCCESS = "#388E3C"
COLOR_WARNING = "#F57C00"
COLOR_INFO = "#0288D1"

# Validation
MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 50
MIN_PASSWORD_LENGTH = 6
MIN_TASK_TITLE_LENGTH = 3
MAX_TASK_TITLE_LENGTH = 200
MAX_TASK_DESCRIPTION_LENGTH = 1000

# UI Spacing
CARD_PADDING = 15
CARD_ELEVATION = 2
DEFAULT_SPACING = 10

# Messages
MSG_ALL_FIELDS_REQUIRED = "All fields required"
MSG_USERNAME_TOO_SHORT = f"Username min. {MIN_USERNAME_LENGTH} characters"
MSG_PASSWORD_TOO_SHORT = f"Password min. {MIN_PASSWORD_LENGTH} characters"
MSG_TITLE_TOO_SHORT = f"Title must be at least {MIN_TASK_TITLE_LENGTH} characters"
MSG_INVALID_EMAIL = "Invalid email format"
